name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Serverless CLI
      run: npm install -g serverless

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy
      run: serverless deploy --stage staging

    - name: Run tests
      run: pytest
